SELECT
mc.campaign_id,
(CASE WHEN CONCAT_WS('_',mc.campaign_id,mc.brand_name)='1_tradershome' THEN 'BLANK'
ELSE mc.campaign_name END) AS campaign_name,
(CASE WHEN CONCAT_WS('_',mc.campaign_id,mc.brand_name)='1_tradershome' THEN 'BLANK'
WHEN mc.campaign_name LIKE 'AC MIX CPA%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'AC MIX CPA Live'
WHEN mc.campaign_name LIKE '%AC Media%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'AC Media Live'
WHEN mc.campaign_name LIKE 'Native%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'AC Native Live'
WHEN mc.campaign_name LIKE '%Accros%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Across Live'
WHEN mc.campaign_name LIKE '%Across%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Across Live'
WHEN mc.campaign_name LIKE 'Apollo%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Apollo Live'
WHEN mc.campaign_name LIKE '%Archie%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Archie Live'
WHEN mc.campaign_name LIKE 'Arya%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Arya Live'
WHEN mc.campaign_name LIKE 'Avri L%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Avri Live'
WHEN mc.campaign_name LIKE 'Axel%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Axel Live'
WHEN mc.campaign_name LIKE 'Bijou%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Bijou Live'
WHEN mc.campaign_name LIKE 'Capital Skills%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Capital Skills Live'
WHEN mc.campaign_name LIKE '%Charlie%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Charlie Live'
WHEN mc.campaign_name LIKE '%CHARLIELEADS%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Charlie Live'
WHEN mc.campaign_name LIKE '%Chloe%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Chloe Live'
WHEN mc.campaign_name LIKE 'Clickmate%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Clickmate Live'
WHEN mc.campaign_name LIKE 'Consul Trading%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Consul Trading Live'
WHEN mc.campaign_name LIKE 'Conversion Master%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Conversion Master Live'
WHEN mc.campaign_name LIKE 'Crypto Tube%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Crypto Tube Live'
WHEN mc.campaign_name LIKE '%CVR%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'CVR Live'
WHEN mc.campaign_name LIKE '%Dem L%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'AC Dem Live'
WHEN mc.campaign_name LIKE '%Dem New%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'AC Dem Live'
WHEN mc.campaign_name LIKE 'AC Dem%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'AC Dem Live'
WHEN mc.campaign_name LIKE '%Fabio%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Fabio Live'
WHEN mc.campaign_name LIKE '%Henry%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Henry Live'
WHEN mc.campaign_name LIKE '%Investor Test%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Investor Test Live'
WHEN mc.campaign_name LIKE '%IP DE%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'IP Live'
WHEN mc.campaign_name LIKE '%IPLEADS%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'IP Live'
WHEN mc.campaign_name LIKE 'Lachi%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Lachi Live'
WHEN mc.campaign_name LIKE 'Libre%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Libre Live'
WHEN mc.campaign_name='LIVE' THEN 'Live'
WHEN mc.campaign_name LIKE '%Loki%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Loki Live'
WHEN mc.campaign_name LIKE 'Maya%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Maya Live'
WHEN mc.campaign_name LIKE '%MIX MARKETING%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'Mix Live'
WHEN mc.campaign_name LIKE '%MIX - TC%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Mix Live'
WHEN mc.campaign_name LIKE '%MIXLIVE%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Mix Live'
WHEN mc.campaign_name LIKE '%UA - MIX%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Mix Live'
WHEN mc.campaign_name LIKE '%MM Inhouse%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'MM Inhouse Live'
WHEN mc.campaign_name LIKE '%MS Leads%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'MS Live'
WHEN mc.campaign_name LIKE '%MS Live%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'MS Live'
WHEN mc.campaign_name LIKE '%MTN%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'MTN Live'
WHEN mc.campaign_name LIKE 'Odie%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Odie Live'
WHEN mc.campaign_name LIKE '%Ollie%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Ollie Live'
WHEN mc.campaign_name LIKE '%Online Book%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Online Book Live'
WHEN mc.campaign_name LIKE 'Online Test%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Online Test Live'
WHEN mc.campaign_name LIKE 'Optimus%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Optimus Live'
WHEN mc.campaign_name LIKE '%Oscar%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Oscar Live'
WHEN mc.campaign_name LIKE '%Pit L%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Pit Live'
WHEN mc.campaign_name LIKE 'Remi L%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Remi Live'
WHEN mc.campaign_name LIKE '%AR RND%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'RND Leads Live'
WHEN mc.campaign_name LIKE '%Ronaldinho%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Ronaldinho Live'
WHEN mc.campaign_name LIKE 'Rosie L%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Rosie Live'
WHEN mc.campaign_name LIKE '%RS Media%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'RS Media Live'
WHEN mc.campaign_name LIKE '%Rose Media%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'RS Media Live'
WHEN mc.campaign_name LIKE '%RS FB%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'RS Media Live'
WHEN mc.campaign_name LIKE '%RSMEDIA%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'RS Media Live'
WHEN mc.campaign_name LIKE '%RS MEDIA%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'RS Media Live'
WHEN mc.campaign_name LIKE '%RS media%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%')  THEN 'RS Media Live'
WHEN mc.campaign_name LIKE '%RS SMS%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'RS Media Live'
WHEN mc.campaign_name LIKE 'Ryder%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Ryder Live'
WHEN mc.campaign_name LIKE '%Sharaabi%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Sharaabi Live'
WHEN mc.campaign_name LIKE '%Simba%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Simba Live'
WHEN mc.campaign_name LIKE '%SIMBALEADS%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Simba Live'
WHEN mc.campaign_name LIKE '%Star L%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Star Live'
WHEN mc.campaign_name LIKE '%Stich%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Stich Live'
WHEN mc.campaign_name LIKE 'Stich L%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Stich Live'
WHEN mc.campaign_name LIKE '%Trader%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Trader Test Live'
WHEN mc.campaign_name LIKE '%TRADERTEST%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Trader Test Live'
WHEN mc.campaign_name LIKE '%TT Inhouse%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'TT Inhouse Live'
WHEN mc.campaign_name LIKE '%Turbo%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Turbo Live'
WHEN mc.campaign_name LIKE 'Vooxo%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Vooxo Live'
WHEN mc.campaign_name LIKE '%WBL%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'WBL Live'
WHEN mc.campaign_name LIKE 'Xeon L%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Xeon Live'
WHEN mc.campaign_name LIKE '%AC Social Live%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'AC Social Live FI'
WHEN mc.campaign_name LIKE '%AR DR NO%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'DR NO Live'
WHEN mc.campaign_name LIKE '%Arlo%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Arlo Live'
WHEN mc.campaign_name LIKE '%Asta%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Asta Live'
WHEN mc.campaign_name LIKE '%Benji%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Benji Live'
WHEN mc.campaign_name LIKE '%Bingo%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Bingo Live'
WHEN mc.campaign_name LIKE '%Bruno%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Bruno Live'
WHEN mc.campaign_name LIKE '%Cleo%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Cleo Live'
WHEN mc.campaign_name LIKE '%Cosmo%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Cosmo Live'
WHEN mc.campaign_name LIKE '%Ebook Online%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Ebook Online Live'
WHEN mc.campaign_name LIKE '%Investing%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Investing Live'
WHEN mc.campaign_name LIKE '%Kisis%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Kisis Live'
WHEN mc.campaign_name LIKE '%Lilly%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Lilly Live'
WHEN mc.campaign_name LIKE '%Lola%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Lola Live'
WHEN mc.campaign_name LIKE '%Lucky%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Lucky Live'
WHEN mc.campaign_name LIKE '%Luna%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Luna Live'
WHEN mc.campaign_name LIKE '%Molly%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Molly Live'
WHEN mc.campaign_name LIKE '%Rocco%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Rocco Live'
WHEN mc.campaign_name LIKE '%Ruby%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Ruby Live'
WHEN mc.campaign_name LIKE '%Sammy%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Sammy Live'
WHEN mc.campaign_name LIKE '%Sandy%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Sandy Live'
WHEN mc.campaign_name LIKE '%Sparky%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Sparky Live'
WHEN mc.campaign_name LIKE '%Tyson%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Tyson Live'
WHEN mc.campaign_name LIKE '%Zeus%' AND (mc.campaign_name LIKE '%LIVE%' OR mc.campaign_name LIKE '%Live%') THEN 'Zeus Live'
ELSE mc.campaign_name END) AS campaign_name_transformed,
mc.brand_name,
CONCAT_WS('_',mc.campaign_id ,mc.brand_name) AS campaign_id_brand,
(CASE WHEN mc.campaign_name LIKE '%Live%' THEN 'LIVE'
WHEN mc.campaign_name LIKE '%LIVE%' THEN 'LIVE'
WHEN mc.campaign_name LIKE '%live%' THEN 'LIVE'
WHEN mc.campaign_name  IS NULL THEN 'NOT LIVE'
ELSE 'NOT LIVE'
END) AS live_not_live
FROM pfx_crm.pfx_campaigns mc